export const cards = [
  {
    
    id: 10,
    user: 1,
    name: 'Скрипт бота продажи цифровых товаров v1, Скрипт бота продажи цифровых товаров v1?',
    description:
      'Бот достаточно простой и в тоже время имеет широкие возможности.Стабильная версия, исправлены многие ошибки.',
    image_1: 'http://botmarketplace.ru/media/products/admin/bot_kfPOiL9.png',
    image_2: 'http://botmarketplace.ru/media/products/admin/bot_ZSMA6IE.png',
    image_3: 'http://botmarketplace.ru/media/products/admin/bot_f6iKpBr.png',
    image_4: 'http://botmarketplace.ru/media/products/admin/bot_HD3xl6U.png',
    video: 'https://www.youtube.com/watch?v=KH7oPMlAaSM',
    article: '53b04a86-ffca-47b7-a51e-48f97390842c',
    price: 100,
    rating: [null, null],
    category: [
      {
        id: 1,
        name: 'Автоматизация заказов',
      },
    ],
    is_favorited: false,
    is_in_shopping_cart: false,
    is_active: true,
    created: '2023-10-03T16:44:40.806820+03:00',
    modified: null,
  },
  {
    id: 9,
    user: 1,
    name: 'Скрипт бота продажи цифровых товаров v1, Скрипт бота продажи цифровых товаров v1',
    description:
      'Бот достаточно простой и в тоже время имеет широкие возможности.Стабильная версия, исправлены многие ошибки.',
    image_1: 'http://botmarketplace.ru/media/products/admin/bot_MUhvRMR.png',
    image_2: 'http://botmarketplace.ru/media/products/admin/bot_WLoQTiS.png',
    image_3: 'http://botmarketplace.ru/media/products/admin/bot_W4VeQUg.png',
    image_4: 'http://botmarketplace.ru/media/products/admin/bot_t9U2xw6.png',
    video: 'https://www.youtube.com/watch?v=KH7oPMlAaSM',
    article: '1c2b6e12-2ebb-425e-83c9-b21e23bf744e',
    price: 100,
    rating: [null, null],
    category: [
      {
        id: 1,
        name: 'Автоматизация заказов',
      },
    ],
    is_favorited: false,
    is_in_shopping_cart: false,
    is_active: true,
    created: '2023-10-03T16:21:00.508444+03:00',
    modified: null,
  },
  {
    id: 5,
    user: 1,
    name: 'October has already come — the grove shakes off the last leaves from its naked branches; The autumn chill has died — the road freezes.The stream still runs murmuring behind the mill123456890!№%;:?Г*',
    description: 'hgfgh12345@%^&',
    image_1: 'http://botmarketplace.ru/media/products/1/bot_Nkvfb8r.png',
    image_2: 'http://botmarketplace.ru/media/products/1/bot_U4VX3Xr.png',
    image_3: 'http://botmarketplace.ru/media/products/1/bot_CX1W91C.png',
    image_4: 'http://botmarketplace.ru/media/products/1/bot_97P3xge.png',
    video: 'https://ya.ru/video/preview/16546652037392511757',
    article: '986d0d13-ff34-49ac-a031-6172454f6a3b',
    price: 500,
    rating: [5, 10],
    category: [
      {
        id: 3,
        name: 'Улучшение обслуживания',
      },
    ],
    is_favorited: false,
    is_in_shopping_cart: false,
    is_active: true,
    created: '2023-10-03T10:50:14.586620+03:00',
    modified: '2023-10-05T17:05:59.014495+03:00',
  },
  {
    id: 4,
    user: 1,
    name: 'Скрипт бота продажи цифровых товаров v1',
    description:
      'Бот достаточно простой и в тоже время имеет широкие возможности.Стабильная версия, исправлены многие ошибки.',
    image_1: 'http://botmarketplace.ru/media/products/admin/bot_8iJXqpW.png',
    image_2: 'http://botmarketplace.ru/media/products/admin/bot_ZM4Eymp.png',
    image_3: 'http://botmarketplace.ru/media/products/admin/bot_eFYlVHI.png',
    image_4: 'http://botmarketplace.ru/media/products/admin/bot_CY8Tr47.png',
    video: 'https://www.youtube.com/watch?v=KH7oPMlAaSM',
    article: 'f10fa037-5f11-4265-9949-fae3c2f570af',
    price: 100,
    rating: [3.5, 15],
    category: [
      {
        id: 1,
        name: 'Автоматизация заказов',
      },
    ],
    is_favorited: false,
    is_in_shopping_cart: false,
    is_active: true,
    created: '2023-10-03T10:40:07.161551+03:00',
    modified: null,
  },
  {
    id: 3,
    user: 1,
    name: 'Бот 2',
    description: 'Описание бота 2',
    image_1: 'http://botmarketplace.ru/media/products/admin/bot_Mc4GQRY.png',
    image_2: null,
    image_3: null,
    image_4: null,
    video: 'https://youtube.be/',
    article: '94ece6df-6840-4789-a751-22d1db510e0f',
    price: 1999,
    rating: [2.28, 38],
    category: [
      {
        id: 3,
        name: 'Улучшение обслуживания',
      },
    ],
    is_favorited: false,
    is_in_shopping_cart: false,
    is_active: true,
    created: '2023-10-03T10:27:37.117554+03:00',
    modified: null,
  },
  {
    id: 2,
    user: 1,
    name: 'Бот 2',
    description: 'Описание бота 2',
    image_1: 'http://botmarketplace.ru/media/products/admin/bot.png',
    image_2: null,
    image_3: null,
    image_4: null,
    video: 'https://youtube.be/',
    article: 'd09e2798-40eb-4075-823c-820842d375b6',
    price: 1999,
    rating: [3.98, 125],
    category: [
      {
        id: 2,
        name: 'Управление заказами',
      },
    ],
    is_favorited: false,
    is_in_shopping_cart: false,
    is_active: true,
    created: '2023-10-03T10:08:30.310649+03:00',
    modified: null,
  },
  {
    id: 1,
    user: 1,
    name: 'Название тестового бота 1',
    description: 'Описание тестового бота 1',
    image_1:
      'http://botmarketplace.ru/media/products/admin/%D0%91%D0%B5%D0%B7_%D0%B8%D0%BC%D0%B5%D0%BD%D0%B8.png',
    image_2: null,
    image_3: null,
    image_4: null,
    video: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    article: 'e99fb4e1-5239-445a-88d8-d6d9c8d75ce5',
    price: 2000,
    rating: [4.5, 2],
    category: [
      {
        id: 4,
        name: 'Персонализация акций',
      },
    ],
    is_favorited: false,
    is_in_shopping_cart: false,
    is_active: true,
    created: '2023-10-02T14:58:16.786983+03:00',
    modified: null,
  },
  {
    id: 75,
    user: 13,
    name: 'Скрипт бота',
    description:
      'Пароль должен быть сложным! В идеале он должен состоять минимум из десяти знаков, среди которых есть цифры, большие и маленькие буквы. И никаких последовательностей – всё в разброс. Пример: Yn8kPi5bN7',
    image_1: 'http://botmarketplace.ru/media/products/13/bot_3p98W1i.png',
    image_2: null,
    image_3: null,
    image_4: null,
    video: 'А зимних праздников блестящие тревоги?',
    article: 'b88cfbeb-5f3b-444c-b82e-da55a933dc25',
    price: 100,
    rating: [null, null],
    category: [],
    is_favorited: false,
    is_in_shopping_cart: false,
    is_active: true,
    created: '2023-10-05T20:34:54.867359+03:00',
    modified: '2023-10-05T20:42:59.357809+03:00',
  },
  {
    id: 74,
    user: 13,
    name: 'Скрипт бота',
    description:
      'Пароль должен быть сложным! В идеале он должен состоять минимум из десяти знаков, среди которых есть цифры, большие и маленькие буквы. И никаких последовательностей – всё в разброс. Пример: Yn8kPi5bN7',
    image_1: 'http://botmarketplace.ru/media/products/13/bot_XkUoQ1Q.png',
    image_2: 'http://botmarketplace.ru/media/products/13/bot_mlzBmUi.png',
    image_3: 'http://botmarketplace.ru/media/products/13/bot_37NTOyp.png',
    image_4: 'http://botmarketplace.ru/media/products/13/bot_EdPsskq.png',
    video: 'А зимних праздников блестящие тревоги?',
    article: 'bcfba32a-61f0-483e-a5fc-2e9ff35bd5fb',
    price: 100,
    rating: [null, null],
    category: [],
    is_favorited: false,
    is_in_shopping_cart: false,
    is_active: true,
    created: '2023-10-05T19:42:09.598351+03:00',
    modified: '2023-10-05T20:39:09.256716+03:00',
  },
  {
    id: 73,
    user: 3,
    name: 'Скрипт бота',
    description:
      'Пароль должен быть сложным! В идеале он должен состоять минимум из десяти знаков, среди которых есть цифры, большие и маленькие буквы. И никаких последовательностей – всё в разброс. Пример: Yn8kPi5bN7',
    image_1: 'http://botmarketplace.ru/media/products/3/bot.png',
    image_2: null,
    image_3: null,
    image_4: null,
    video: 'А зимних праздников блестящие тревоги?',
    article: 'e5f6973c-a16d-47a4-9e73-f069efde36d5',
    price: -100,
    rating: [null, null],
    category: [],
    is_favorited: false,
    is_in_shopping_cart: false,
    is_active: true,
    created: '2023-10-05T18:59:33.934026+03:00',
    modified: null,
  },
  {
    id: 72,
    user: 2,
    name: 'Скрипт бота',
    description:
      'Пароль должен быть сложным! В идеале он должен состоять минимум из десяти знаков, среди которых есть цифры, большие и маленькие буквы. И никаких последовательностей – всё в разброс. Пример: Yn8kPi5bN7',
    image_1: 'http://botmarketplace.ru/media/products/2/bot_bkL1syU.png',
    image_2: null,
    image_3: null,
    image_4: null,
    video: 'А зимних праздников блестящие тревоги?',
    article: '453818e4-a8cc-418f-86a8-82883b980752',
    price: -100,
    rating: [null, null],
    category: [],
    is_favorited: false,
    is_in_shopping_cart: false,
    is_active: true,
    created: '2023-10-05T16:21:19.591117+03:00',
    modified: null,
  },
  {
    id: 71,
    user: 2,
    name: 'Скрипт бота',
    description:
      'Пароль должен быть сложным! В идеале он должен состоять минимум из десяти знаков, среди которых есть цифры, большие и маленькие буквы. И никаких последовательностей – всё в разброс. Пример: Yn8kPi5bN7',
    image_1: 'http://botmarketplace.ru/media/products/2/bot_bkL1syU.png',
    image_2: null,
    image_3: null,
    image_4: null,
    video: 'А зимних праздников блестящие тревоги?',
    article: '453818e4-a8cc-418f-86a8-82883b980752',
    price: -100,
    rating: [null, null],
    category: [],
    is_favorited: false,
    is_in_shopping_cart: false,
    is_active: true,
    created: '2023-10-05T16:21:19.591117+03:00',
    modified: null,
  },
];
