[
  ['POST', `/auth/token/login/`],
  ['POST', `/auth/token/logout/`],

  ['GET', `/cart/`],
  ['GET', `/cart/${id}/`],

  ['GET', `/categories/`],
  ['GET', `/categories/${id}/`],

  ['GET', `/orders/`],
  ['POST', `/orders/`],
  ['GET', `/orders/${id}/`],
  ['PUT', `/orders/${id}/`],
  ['PATCH', `/orders/${id}/`],
  ['DELETE', `/orders/${id}/`],

  ['GET', `/products/`],
  ['POST', `/products/`],
  ['GET', `/products/${id}/`],
  ['PUT', `/products/${id}/`],
  ['PATCH', `/products/${id}/`],
  ['DELETE', `/products/${id}/`],
  ['POST', `/products/${id}/favorite/`],
  ['DELETE', `/products/${id}/favorite/`],
  ['POST', `/products/${id}/shopping_cart/`],
  ['DELETE', `/products/${id}/shopping_cart/`],
  ['GET', `/products/${product_id}/reviews/`],
  ['POST', `/products/${product_id}/reviews/`],
  ['GET', `/products/${product_id}/reviews/${id}/`],
  ['PUT', `/products/${product_id}/reviews/${id}/`],
  ['PATCH', `/products/${product_id}/reviews/${id}/`],
  ['DELETE', `/products/${product_id}/reviews/${id}/`],

  ['GET', `/users/`],
  ['POST', `/users/`],
  ['GET', `/users/${id}/`],
  ['PUT', `/users/${id}/`],
  ['PATCH', `/users/${id}/`],
  ['DELETE', `/users/${id}/`],
  ['POST', `/users/activation/`],
  ['GET', `/users/me/`],
  ['PUT', `/users/me/`],
  ['PATCH', `/users/me/`],
  ['DELETE', `/users/me/`],
  ['POST', `/users/resend_activation/`],
  ['POST', `/users/reset_email/`],
  ['POST', `/users/reset_email_confirm/`],
  ['POST', `/users/reset_password/`],
  ['POST', `/users/reset_password_confirm/`],
  ['POST', `/users/set_email/`],
  ['POST', `/users/set_password/`],
];
